version: 2.1

orbs:
  docker: circleci/docker@2.0.1

workflows: 
  commit:
    jobs:
      - run_tests
      - build-and-push:
          requires:
            - "run_tests"
          filters:
            branches:
              only:
                - master
                - main

jobs:
  run_tests:
    working_directory: ~/react-ops
    docker:
      - image: circleci/node:12.19.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: docker-build
          command: 'docker build -t react-ops-container -f Dockerfile.dev .'
      - run:
          name: docker-test
          command: 'docker run -e CI=true -p 8080:80 react-ops-container npm run test -- --coverage'
  build-and-push:
    environment:
      DOCKER_IMAGE: react-ops
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_USER/$DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_USER/$DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
